# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20161216_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=80)),
                ('event_date', models.DateField()),
                ('event_duration', models.PositiveIntegerField()),
                ('event_description', models.TextField()),
            ],
        ),
    ]
