# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
