# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_events_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_image',
        ),
        migrations.AddField(
            model_name='events',
            name='event_contact',
            field=models.CharField(default='sainath', max_length=50),
            preserve_default=False,
        ),
    ]
