# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_forum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forum',
        ),
    ]
