# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_delete_forum'),
    ]

    operations = [
        migrations.CreateModel(
            name='mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world', models.CharField(max_length=10)),
            ],
        ),
    ]
