# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20161230_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='formRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=50)),
                ('form_fathersName', models.CharField(max_length=50)),
                ('form_required', models.CharField(max_length=50)),
                ('form_reason', models.TextField()),
                ('form_status', models.CharField(default='processing', max_length=50)),
            ],
        ),
    ]
