# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_formrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flexi_core', models.IntegerField()),
                ('bouquet_core', models.IntegerField()),
                ('it_elective', models.IntegerField()),
                ('maths_science', models.IntegerField()),
                ('humanities', models.IntegerField()),
                ('skills', models.IntegerField()),
                ('btp', models.IntegerField()),
                ('free_elective', models.IntegerField()),
            ],
        ),
    ]
