# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_course_course_credits'),
        ('portal', '0014_auto_20170125_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Course')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Students')),
            ],
        ),
    ]
