# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='year',
            field=models.IntegerField(),
        ),
    ]
