# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20170125_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credits',
            name='btp',
        ),
        migrations.RemoveField(
            model_name='credits',
            name='maths_science',
        ),
        migrations.AddField(
            model_name='credits',
            name='additional_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credits',
            name='btp_honors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credits',
            name='maths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credits',
            name='rigid_core',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credits',
            name='science',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credits',
            name='student',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='portal.Students'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credits',
            name='bouquet_core',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='credits',
            name='flexi_core',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='credits',
            name='free_elective',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='credits',
            name='humanities',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='credits',
            name='it_elective',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='credits',
            name='skills',
            field=models.IntegerField(default=0),
        ),
    ]
