# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20170224_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credits',
            old_name='flexi_core',
            new_name='core',
        ),
        migrations.RemoveField(
            model_name='credits',
            name='rigid_core',
        ),
    ]
