# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20170224_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credits',
            name='student',
        ),
        migrations.AddField(
            model_name='credits',
            name='student_roll_no',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
    ]
