# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20170118_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_credits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
