# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_course_course_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_sem',
            field=models.CharField(default='spring', max_length=7),
            preserve_default=False,
        ),
    ]
