# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_course_course_sem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_rollno', models.CharField(max_length=11)),
                ('course_title', models.CharField(max_length=50)),
                ('present', models.TextField(default='0-0-0000')),
                ('absent', models.TextField(default='0-0-0000')),
            ],
        ),
        migrations.CreateModel(
            name='Attendancefiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
