# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_attendance_attendancefiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'')),
            ],
        ),
    ]
