# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 09:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_creditdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='absent',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='present',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2017, 2, 25)),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='H', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student_rollno',
            field=models.CharField(max_length=9),
        ),
    ]
