# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 06:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_auto_20170225_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2017, 2, 26)),
        ),
    ]
